#!/usr/bin/env bash

### DEFAULT PROGRAM ARGUMENTS ###
KEYWORD=""
DATA=""
LABEL=""
ALL=false
CONTAINS=false
SAVE=false
STRING_CASE=""
DELETE=false
DELETE_ALL=false
DB_PATH=/var/gime/data.db

### USAGE & PROGRAM ARGUMENTS PARSING ###
function usage() {
    printf "$1"
cat << EOF
Usage: gime <KEYWORD> [flags] - Display data associated with a given keyword.
-h      --help                          Display program usage
-a      --all                           Display all stored data
-c      --contains                      Display all data that contains <KEYWORD>
-l      --label         <LABEL>         Set a label in saving mode. Filter by label in display mode 
-i      --insensitive                   Set case insensitive in display mode
-s      --save          <DATA>          Save <DATA> with the corresponding <KEYWORD>
-d      --delete                        Delete data that corresponds to <KEYWORD>
-da     --delete-all                    Delete all saved data
EOF
    exit
}

[[ "$#" == "0" ]] && usage
while :; do
    case "$1" in
        -h|--help)
            usage
        ;;
        -a|--all)
            ALL=true; break
        ;;
        -c|--contains)
            CONTAINS=true
        ;;
        -s|--save)
            [[ "$2" != "" ]] && SAVE=true; DATA=$(echo "$2"); shift || usage "Wrong usage.\n"
        ;;
        -l|--label)
            [[ "$2" != "" ]] && LABEL=$(echo "$2"); shift || usage "Wrong usage.\n"
        ;;
        -i|--insensitive)
            STRING_CASE="collate nocase"
        ;;
        -d|--delete)
            DELETE=true
        ;;
        -da|--delete-all)
            DELETE_ALL=true; break
        ;;
        "")
            break
        ;;
        ?*)
            KEYWORD="$1"
        ;;
        *)
            usage "Wrong usage.\n"
        ;;
    esac
    shift
done


### MAIN PROGRAM ###
if $DELETE_ALL; then
    sqlite3 -batch "${DB_PATH}" "delete from saved_data"
elif $DELETE; then
    if [[ "$LABEL" != "" ]]; then
        sqlite3 -batch "${DB_PATH}" "delete from saved_data where keyword='${KEYWORD}' and label='${LABEL}'"
    else
        sqlite3 -batch "${DB_PATH}" "delete from saved_data where keyword='${KEYWORD}'"
    fi
elif $SAVE; then
    sqlite3 -batch "${DB_PATH}" "insert into saved_data values('${KEYWORD}','${LABEL}','${DATA}')"
elif $ALL; then
    sqlite3 -batch "${DB_PATH}" "select * from saved_data"
else
    if $CONTAINS; then
        KEYWORD="%$KEYWORD%"
    fi
    if [[ "$LABEL" != "" ]]; then
        sqlite3 -batch "${DB_PATH}" "select data from saved_data where keyword='${KEYWORD}' ${STRING_CASE} and label='${LABEL}' ${STRING_CASE}"
    else
        sqlite3 -batch "${DB_PATH}" "select data from saved_data where keyword='${KEYWORD}' ${STRING_CASE}"
    fi
fi
